### ISSUE TITLE
[Question] Is the copyright year 2019 correct?

### ISSUE THREAD

**Issue by fneitzel** [hhvm/hacklang.org#26]
I visited hacklang and saw 2019 in the footer:

![image](https://user-images.githubusercontent.com/10213803/84083948-d9ccc480-a9e2-11ea-94dd-efa8a669d683.png)

I don't know if this is supposed to be like that.

https://github.com/hhvm/hacklang.org/blob/999e7b56276aaeb045dc0d94dee4e430006c3965/website/siteConfig.js#L84

**Comment by jjergus** [comment]
I'd guess this is probably correct -- if someone makes changes to hacklang.org, the site gets redeployed and the code you quoted should automatically update the year. Since no one made any changes in 2020 yet, "Copyright 2019" is probably correct. I'll close this for now but feel free to reopen if I missed anything.
